### ISSUE TITLE
Please add support for a single consumer class that consumes multiple message types

### ISSUE THREAD

**Issue by peter-nguyen-contemi** [PandaTechAM/be-lib-masstransit-postgres-outbox#10]
A MassTransit consumer class may consume multiple message types by implementing the IConsumer with various message type arguments, for example

```csharp
public class CustomerEventsConsumers :
    IConsumer<CustomerCreated>,
    IConsumer<CustomerUpdated>
{
    public Task Consume(ConsumeContext<CustomerCreated> context)
    {
        ...
    }

    public Task Consume(ConsumeContext<CustomerUpdated> context)
    {
        ...
    }
}
```

With the current design of this package, inbox consumer classes have to extend the InboxConsumer base class, which limit the ability for an inbox consumer to consumer more than one message type (C# does not allow multiple inheritance). It would be nice to have a built-in support for this feature.

**Comment by HaikAsatryan** [comment]
Hello @peter-nguyen-contemi,

Thank you for bringing up this suggestion and for your patience while we reviewed it.

We understand your use case and the desire for a consumer to handle multiple message types simultaneously. However, we do not plan to support this feature in the `Pandatech.MassTransit.PostgresOutbox` package. Let us explain the rationale:

## Design Considerations

- **Single Responsibility Principle:** A consumer handling multiple message types introduces additional complexity and can violate the single responsibility principle. Each consumer should ideally focus on a single, well-defined task. Combining responsibilities may lead to harder-to-maintain and less testable code.

- **MassTransit’s Design Philosophy:** The MassTransit framework encourages small, single-purpose consumers for clarity and separation of concerns. This approach ensures that the logic for handling each message type remains modular and focused.

- **Dependency and Lifecycle Management**: A consumer handling multiple types might have dependencies or behaviors that differ across the message types. Managing these effectively within a single class could result in intricate code and potential issues during dependency injection and message routing.

## Technical Challenges
From a technical perspective, extending the `InboxConsumer` base class for multiple message types would require significant architectural changes. .NET does not support multiple inheritance, and introducing workarounds (e.g., composition-based patterns) might increase the complexity of both usage and maintenance.

## Suggested Solution

We recommend introducing two separate consumers, each handling a distinct message type. This approach is consistent with the design principles of MassTransit and allows for better scalability and maintainability of your codebase.
-------------------
We hope this explanation provides clarity, and we appreciate your understanding. Thank you again for your feedback and for being part of our community. If you have further questions or need assistance, feel free to reach out!
